### ISSUE TITLE
Entity not available as an alarm panel card

### ISSUE THREAD

**Issue by allandf** [RenierM26/hass_ids_hyyp#2]
Thanks for taking the time to share the integration. Installing the integration appears to be successful as I can see the device. However, I have the following error log:

Logger: homeassistant.components.alarm_control_panel
Source: custom_components/ids_hyyp/alarm_control_panel.py:70
Integration: Alarm Control Panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 17:32:03 (3 occurrences)
Last logged: 17:35:03

Error while setting up ids_hyyp platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ids_hyyp/alarm_control_panel.py", line 38, in async_setup_entry
    [
  File "/config/custom_components/ids_hyyp/alarm_control_panel.py", line 39, in <listcomp>
    HyypAlarm(coordinator, site_id, partition_id, arm_code)
  File "/config/custom_components/ids_hyyp/alarm_control_panel.py", line 70, in __init__
    self._arm_home_profile_id = list(self.partition_data["stayProfiles"])[
IndexError: list index out of range

Configured with hyyp247 option.

**Comment by RenierM26** [comment]
Hi @allandf,

Do you have any stay profiles configured on your alarm?

**Comment by allandf** [comment]
Hi @RenierM26,

I am relatively new to HYYP, I have several partitions through the application but I only have the option to arm them, not stay, so I suspect that I don't have any stay profiles. This would make sense given the error message. I will try see if I can figure out how to setup a stay profile and re-install to check if that fixes the problem.

**Comment by allandf** [comment]
![stay_arm](https://user-images.githubusercontent.com/37168229/173246294-e0fcdd9f-9c93-4613-bdec-4114fa634644.jpg)

Hi @RenierM26, 

I managed to get a stay profile stored, as you can see in the figure above its also visible in HYYP, unfortunately I am still getting the same error as in the first message after re-installing the integration and multiple restarts. Any other suggestions?

**Comment by allandf** [comment]
This issue was resolved with an update, thanks!
