### ISSUE TITLE
Intergration not loaded after update 2023.4

### ISSUE THREAD

**Issue by valpre09** [RenierM26/hass_ids_hyyp#9]
Updated to OS 2023.4 and intergration isnt loading.

Log as follows:

Logger: homeassistant.setup
Source: setup.py:213
First occurred: 12:40:32 (1 occurrences)
Last logged: 12:40:32

Setup failed for custom integration ids_hyyp: Unable to import component: Exception importing custom_components.ids_hyyp

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/ids_hyyp/__init__.py:6
Integration: IDS Hyyp(Beta)
First occurred: 12:40:32 (5 occurrences)
Last logged: 12:43:37

Unexpected exception importing component custom_components.ids_hyyp
Unexpected exception importing platform custom_components.ids_hyyp.application_credentials
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ids_hyyp/__init__.py", line 6, in <module>
    from pyhyypapi import HyypClient
  File "/usr/local/lib/python3.10/site-packages/pyhyypapi/__init__.py", line 6, in <module>
    from .push_receiver import run_example
  File "/usr/local/lib/python3.10/site-packages/pyhyypapi/push_receiver.py", line 25, in <module>
    from .android_checkin_pb2 import AndroidCheckinProto, ChromeBuildProto
  File "/usr/local/lib/python3.10/site-packages/pyhyypapi/android_checkin_pb2.py", line 36, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Also i see the Hyyp app was recenlty updated with a new panic button ferature, would be great to have this as a new entity

**Comment by Owewolf** [comment]
Not that my IDS Hyyp integration loaded as I still have the problem with loading both sites Ito my integration, I now have the same errors you received so it appears the upgraded broke it good.

**Comment by Owewolf** [comment]
My error

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/ids_hyyp/__init__.py:6 
Integration: ids_hyyp 
First occurred: 19:00:09 (7 occurrences) 
Last logged: 19:02:41

Unexpected exception importing component custom_components.ids_hyyp
Unexpected exception importing platform custom_components.ids_hyyp.config_flow
Unexpected exception importing platform custom_components.ids_hyyp.application_credentials
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ids_hyyp/__init__.py", line 6, in <module>
    from pyhyypapi import HyypClient
  File "/usr/local/lib/python3.10/site-packages/pyhyypapi/__init__.py", line 6, in <module>
    from .push_receiver import run_example
  File "/usr/local/lib/python3.10/site-packages/pyhyypapi/push_receiver.py", line 25, in <module>
    from .android_checkin_pb2 import AndroidCheckinProto, ChromeBuildProto
  File "/usr/local/lib/python3.10/site-packages/pyhyypapi/android_checkin_pb2.py", line 36, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by valpre09** [comment]
Ya rolled back to 2023.3 and working again. will hold off a week or so before upgrading again and see if this gets updated

**Comment by Owewolf** [comment]
Hope it can be fixed for you I'm still unable to get it loaded it has hassles withe the site(partition) integration after authenticating me, however now it's unable to even authenticate.

**Comment by allandf** [comment]
Was working 100% until the update now I am getting the same error.

**Comment by hawky358** [comment]
@valpre09 @Owewolf @allandf 

Hello there,
From activity it seems like the dev is on hiatus or quit.

I have forked the repo and fixed this specific issue. See [https://github.com/hawky358/hass_ids_hyyp](https://github.com/hawky358/hass_ids_hyyp)
